mpp_practic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simpleapp.urls')),
]

simpleapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from simpleapp import views

app_name = 'simpleapp'
urlpatterns = [
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('index/', views.index, name='index'),
    path('notify/', views.notify, name='notify'),

    path('entis/<int:varsta>', views.EntityList.as_view()),
]

simpleapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class MyUser(AbstractUser):
    def __str__(self):
        return f'{self.username} {self.email}'


class Entity(models.Model):
    user = models.OneToOneField(MyUser, models.CASCADE, related_name='entity')
    varsta = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username + " " + str(self.varsta)

simpleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from ws4redis.publisher import RedisPublisher
from ws4redis.redis_store import RedisMessage

from simpleapp.models import Entity
from simpleapp.serializer import EntitySerializer

redis_publisher = RedisPublisher(facility='here', broadcast=True)
message = RedisMessage('Refresh ^^')


@login_required
def index(request):
    return render(request, 'index.html', {'utilizator': request.user})


def notify(request):
    redis_publisher.publish_message(message)


class EntityList(APIView):
    def get(self, request, varsta):
        entis = Entity.objects.filter(varsta=varsta)
        serializer = EntitySerializer(entis, many=True)
        return Response(serializer.data)

simpleapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Pagina de index </title>
</head>
<body>

    <a href="{% url 'simpleapp:logout' %}"> Logout </a> <br>
    <a href="{% url 'simpleapp:notify' %}"> Notify </a> <br>

    Welcome {{ utilizator }}

</body>

<script>
    let ws = new WebSocket('ws://localhost:8000/ws/here?subscribe-broadcast');
        ws.onopen = function() {
            console.log("websocket connected");
        };
        ws.onmessage = function(e) {
            console.log("Received: " + e.data);
            location.reload();
        };
        ws.onerror = function(e) {
            console.error(e);
        };
        ws.onclose = function(e) {
            console.log("connection closed");
        };
</script>

</html>

simpleapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Login</title>
</head>
<body>

    <h2>Login</h2>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>

</body>
</html>